### ISSUE TITLE
autoformly for only one or two fields

### ISSUE THREAD

**Issue by maxfriedmann** [wieldo/meteor-autoformly#2]
Hi,
great project so far. I've been looking into something similar since the original aldeed:autoform package hardly plays together with angular. What I like about the aldeed:autoform package is, that I can display a single field with validation etc. 

Is that already possible with this package? I cannot display a form for the complete object since we have a mechanism that takes care of foreign keys via search, e.g.:

![image](https://cloud.githubusercontent.com/assets/2809483/11507658/5e304890-9855-11e5-898c-86a2661df41d.png)

So some fields would need a manual implementation on our side which is fine. But for the rest I would like to use your package!

**Comment by kamilkisiela** [comment]
Hi, glad to hear :)

I don't know if i really understand what you want to achieve but yes, there is an option to do it. 

Basically, forms are generated by [angular-formly](http://angular-formly.com). This package reads SimpleSchema and outputs angular-formly directive with proper configuration.

You can use [filtering](https://github.com/wieldo/meteor-autoformly/tree/master#convert-selected-collection-fields). If you're using auto-formly component you can put these options in "options" directive.

```
<auto-formly
    collection="vm.booksCollection"
    doc="vm.book"
    options="vm.options">
    <button type="submit">Update</button>
</auto-formly>
```

Where:
- _collection_ is ... obvious :)
- _doc_ is a collection object
- _options_ you can use to filtering

If your collection has few fields and you want to display only one of them in the form, here are example options with filtering:

```
{
    all: false, // hide all
    fields: { // display only those fields
        firstname: true // or field configuration for angular-formly
    }
}
```

or if you want to overwrite autoFormly's auto-generated configuration used in [angular-formly](http://angular-formly.com) just put [configuration object](http://docs.angular-formly.com/docs/field-configuration-object) as property value (instead of `true`). Be aware that extending auto-generated configuration is still in progress so there might be problems.

AutoFormly uses [formlyMaterial](http://github.com/wieldo/angular-formly-templates-material). This is a template for angular-formly totally wrote by me so forms have material look. It's achieved by using angular-material components (>= 0.11.0).

And I know, documentation is very poor but unfortunately, I've got a lot of work at the moment.

**Comment by maxfriedmann** [comment]
Well, thanks for that outstanding helpful answer. That is exactly what we need. 

Thanks a lot!!!
